[build]
  command = "npm run build"
  publish = "build"
  node_version = "18.19.1"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 