services:
  - type: web
    name: food-delivery-backend
    env: node
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
